/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gestionmedicale.vues;

import com.gestionmedicale.controlleurs.ControlleurMedicament;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Manel
 */
public class GestionMedicament extends javax.swing.JFrame {

    /**
     * Creates new form GestionMarques
     */
    public GestionMedicament() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAjouter = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPrix = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxCode_Ordonnance = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedicaments = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldFiltreOrdonnance = new javax.swing.JTextField();
        jCheckBoxFiltreOrdonnance = new javax.swing.JCheckBox();
        jButtonExit = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 9));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 90));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestionmedicale/images/checklist.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel2.setText("Gestion Des Médicaments");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 24))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(450, 165));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 200));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButtonAjouter.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestionmedicale/images/add.png"))); // NOI18N
        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 150, 0, 0);
        jPanel2.add(jButtonAjouter, gridBagConstraints);

        jButtonSupprimer.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestionmedicale/images/remove.png"))); // NOI18N
        jButtonSupprimer.setText("Supprimer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 150);
        jPanel2.add(jButtonSupprimer, gridBagConstraints);

        jButtonModifier.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestionmedicale/images/pencil.png"))); // NOI18N
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jPanel2.add(jButtonModifier, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Prix");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jTextFieldPrix.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 8);
        jPanel2.add(jTextFieldPrix, gridBagConstraints);

        jTextFieldNom.setMinimumSize(new java.awt.Dimension(120, 30));
        jTextFieldNom.setPreferredSize(new java.awt.Dimension(120, 30));
        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel2.add(jTextFieldNom, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Nom");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("ID Ordonnance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel10, gridBagConstraints);

        jComboBoxCode_Ordonnance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucun" }));
        jComboBoxCode_Ordonnance.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel2.add(jComboBoxCode_Ordonnance, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 7, 2, 7);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des médicaments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 24))); // NOI18N
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 200));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jTableMedicaments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMedicaments);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Filter par Ordonnance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 13);
        jPanel3.add(jLabel11, gridBagConstraints);

        jTextFieldFiltreOrdonnance.setMinimumSize(new java.awt.Dimension(250, 30));
        jTextFieldFiltreOrdonnance.setPreferredSize(new java.awt.Dimension(250, 30));
        jTextFieldFiltreOrdonnance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiltreOrdonnanceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jTextFieldFiltreOrdonnance, gridBagConstraints);

        jCheckBoxFiltreOrdonnance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBoxFiltreOrdonnance.setText("Filtre Par Ordonnance");
        jCheckBoxFiltreOrdonnance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltreOrdonnanceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        jPanel3.add(jCheckBoxFiltreOrdonnance, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        getContentPane().add(jPanel3, gridBagConstraints);

        jButtonExit.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestionmedicale/images/exit.png"))); // NOI18N
        jButtonExit.setText("Exit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 5, 40);
        getContentPane().add(jButtonExit, gridBagConstraints);

        jButtonRetour.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButtonRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestionmedicale/images/left.png"))); // NOI18N
        jButtonRetour.setText("Retour");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 5, 40);
        getContentPane().add(jButtonRetour, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jTextFieldFiltreOrdonnanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiltreOrdonnanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFiltreOrdonnanceActionPerformed

    private void jCheckBoxFiltreOrdonnanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltreOrdonnanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFiltreOrdonnanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               GestionMedicament vue = new GestionMedicament();
                ControlleurMedicament c = new ControlleurMedicament(vue);
                vue.setVisible(true);
            }
        });
    }

    public JButton getjButtonAjouter() {
        return jButtonAjouter;
    }

    public JButton getjButtonExit() {
        return jButtonExit;
    }

    public JButton getjButtonModifier() {
        return jButtonModifier;
    }

    public JButton getjButtonRetour() {
        return jButtonRetour;
    }

    public JButton getjButtonSupprimer() {
        return jButtonSupprimer;
    }

    public JCheckBox getjCheckBoxFiltreOrdonnance() {
        return jCheckBoxFiltreOrdonnance;
    }

    public JComboBox getjComboBoxCode_Ordonnance() {
        return jComboBoxCode_Ordonnance;
    }

    public JTable getjTableMedicaments() {
        return jTableMedicaments;
    }    

    public JTextField getjTextFieldFiltreOrdonnance() {
        return jTextFieldFiltreOrdonnance;
    }

    public JTextField getjTextFieldNom() {
        return jTextFieldNom;
    }

    public JTextField getjTextFieldPrix() {
        return jTextFieldPrix;
    }

    public void setjButtonAjouter(JButton jButtonAjouter) {
        this.jButtonAjouter = jButtonAjouter;
    }

    public void setjButtonExit(JButton jButtonExit) {
        this.jButtonExit = jButtonExit;
    }

    public void setjButtonModifier(JButton jButtonModifier) {
        this.jButtonModifier = jButtonModifier;
    }

    public void setjButtonRetour(JButton jButtonRetour) {
        this.jButtonRetour = jButtonRetour;
    }

    public void setjButtonSupprimer(JButton jButtonSupprimer) {
        this.jButtonSupprimer = jButtonSupprimer;
    }

    public void setjCheckBoxFiltreOrdonnance(JCheckBox jCheckBoxFiltreOrdonnance) {
        this.jCheckBoxFiltreOrdonnance = jCheckBoxFiltreOrdonnance;
    }

    public void setjComboBoxCode_Ordonnance(JComboBox jComboBoxCode_Ordonnance) {
        this.jComboBoxCode_Ordonnance = jComboBoxCode_Ordonnance;
    }

    public void setjTableMedicaments(JTable jTableMedicaments) {
        this.jTableMedicaments = jTableMedicaments;
    }
    
    public void setjTextFieldFiltreOrdonnance(JTextField jTextFieldFiltreOrdonnance) {
        this.jTextFieldFiltreOrdonnance = jTextFieldFiltreOrdonnance;
    }

    public void setjTextFieldNom(JTextField jTextFieldNom) {
        this.jTextFieldNom = jTextFieldNom;
    }

    public void setjTextFieldPrix(JTextField jTextFieldPrix) {
        this.jTextFieldPrix = jTextFieldPrix;
    }

    
    

   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JCheckBox jCheckBoxFiltreOrdonnance;
    private javax.swing.JComboBox jComboBoxCode_Ordonnance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedicaments;
    private javax.swing.JTextField jTextFieldFiltreOrdonnance;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrix;
    // End of variables declaration//GEN-END:variables
}
