/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gestionmedicale.vues;

//import controlleurs.ControlleurMenu;
import com.gestionmedicale.controlleurs.ControlleurMenu;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Aymen
 */
public class Menu extends javax.swing.JFrame
{

    /**
     * Creates new form Menu
     */
    public Menu()
    {
        initComponents();
       // this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/IconMenu.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonGestionOrdonnances = new javax.swing.JButton();
        jButtonGestionMedicaments = new javax.swing.JButton();
        jButtonGestionPatients = new javax.swing.JButton();
        jButtonGestionMedecins = new javax.swing.JButton();
        jButtonGestionCabinets = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setName("FrameMenu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(650, 550));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 250));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setText("Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestionmedicale/images/websitee.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 550));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButtonGestionOrdonnances.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jButtonGestionOrdonnances.setText("Gestion Odonnances");
        jButtonGestionOrdonnances.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonGestionOrdonnances.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonGestionOrdonnances.setPreferredSize(new java.awt.Dimension(180, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(16, 31, 16, 31);
        jPanel2.add(jButtonGestionOrdonnances, gridBagConstraints);

        jButtonGestionMedicaments.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jButtonGestionMedicaments.setText("Gestion Médicaments");
        jButtonGestionMedicaments.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonGestionMedicaments.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonGestionMedicaments.setPreferredSize(new java.awt.Dimension(180, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(16, 31, 16, 31);
        jPanel2.add(jButtonGestionMedicaments, gridBagConstraints);

        jButtonGestionPatients.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jButtonGestionPatients.setText("Gestion Patients");
        jButtonGestionPatients.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonGestionPatients.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonGestionPatients.setPreferredSize(new java.awt.Dimension(180, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jButtonGestionPatients, gridBagConstraints);

        jButtonGestionMedecins.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jButtonGestionMedecins.setText("Gestion Médecins");
        jButtonGestionMedecins.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonGestionMedecins.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonGestionMedecins.setPreferredSize(new java.awt.Dimension(180, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jButtonGestionMedecins, gridBagConstraints);

        jButtonGestionCabinets.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jButtonGestionCabinets.setText("Gestion Cabinets");
        jButtonGestionCabinets.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonGestionCabinets.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonGestionCabinets.setPreferredSize(new java.awt.Dimension(180, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 16, 0);
        jPanel2.add(jButtonGestionCabinets, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Menu vueMenu=new Menu();
                ControlleurMenu controlleurMenu=new ControlleurMenu(vueMenu);
                vueMenu.setVisible(true);
            }
        });
    }

    public JButton getjButtonGestionCabinets() {
        return jButtonGestionCabinets;
    }

    public JButton getjButtonGestionMedecins() {
        return jButtonGestionMedecins;
    }

    public JButton getjButtonGestionMedicaments() {
        return jButtonGestionMedicaments;
    }

    public JButton getjButtonGestionOrdonnances() {
        return jButtonGestionOrdonnances;
    }

    public JButton getjButtonGestionPatients() {
        return jButtonGestionPatients;
    }

    public void setjButtonGestionCabinets(JButton jButtonGestionCabinets) {
        this.jButtonGestionCabinets = jButtonGestionCabinets;
    }

    public void setjButtonGestionMedecins(JButton jButtonGestionMedecins) {
        this.jButtonGestionMedecins = jButtonGestionMedecins;
    }

    public void setjButtonGestionMedicaments(JButton jButtonGestionMedicaments) {
        this.jButtonGestionMedicaments = jButtonGestionMedicaments;
    }

    public void setjButtonGestionOrdonnances(JButton jButtonGestionOrdonnances) {
        this.jButtonGestionOrdonnances = jButtonGestionOrdonnances;
    }

    public void setjButtonGestionPatients(JButton jButtonGestionPatients) {
        this.jButtonGestionPatients = jButtonGestionPatients;
    }

    
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGestionCabinets;
    private javax.swing.JButton jButtonGestionMedecins;
    private javax.swing.JButton jButtonGestionMedicaments;
    private javax.swing.JButton jButtonGestionOrdonnances;
    private javax.swing.JButton jButtonGestionPatients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}